# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_app', '0002_auto_20160617_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='time_click',
            field=models.DateTimeField(),
        ),
    ]
